# Generated by Django 4.1.7 on 2023-04-14 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('product__name',)},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество'),
        ),
    ]
