# Generated by Django 4.1.7 on 2023-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='uid_erp',
            field=models.CharField(blank=True, max_length=40, verbose_name='Идентификатор в ERP'),
        ),
    ]
