# Generated by Django 4.1.7 on 2023-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid_erp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Идентификатор в ERP'),
        ),
    ]
